# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-13 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=30)),
            ],
        ),
    ]
