# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-17 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_details',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
